- name: Assure the shell we want is a allowed
  tags: set_default_shell
  when: ansible_distribution == 'MacOSX'
  lineinfile: dest=/etc/shells line="{{default_shell}}"
- name: Set our default shell
  tags: set_default_shell
  when: ansible_distribution == 'MacOSX'
  command: chpass -s "{{default_shell}}" "{{lookup('env','USER')}}"
