---
- name: MacOSX
  tags: chrome
  when: ansible_distribution == 'MacOSX'
  homebrew_cask:
    name: google-chrome
    state: present

- name: Ubuntu
  tags: chrome
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: chromium-browser
    state: latest
