---

- name: MacOSX
  tags: latex
  when: ansible_distribution == 'MacOSX'
  homebrew_tap:
    name: miktex/miktex
    state: present

- name: MacOSX
  tags: latex
  when: ansible_distribution == 'MacOSX'
  with_items: "{{packages[ansible_distribution | lower]}}"
  homebrew:
    name: "{{item}}"
    state: latest

- name: Ubuntu
  tags: latex
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  with_items: "{{packages[ansible_distribution | lower]}}"
  package:
    name: "{{item}}"
    state: latest
