---
- name: python 2 package
  tags: ansible-lint
  become: !!bool yes
  pip:
    name: ansible-lint
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
