- name: Add Taps
  homebrew_tap: name="{{item}}" state=present
  with_items: "{{homebrew_taps}}"
  when: ansible_distribution == 'MacOSX'

- name: Install packages with homebrew
  homebrew:
    name: "{{item.name}}"
    options: "{{item.options|default()}}"
    state: latest
  with_items: "{{homebrew_packages}}"
  when: ansible_distribution == 'MacOSX'

- name: Install packages with homebrew cask
  homebrew_cask: name="{{item}}" state=installed
  with_items: "{{homebrew_cask_packages}}"
  when: ansible_distribution == 'MacOSX'

- name: Update all packages
  homebrew: update_homebrew=yes
  when: ansible_distribution == 'MacOSX'
