- name: Add Taps
  tags: homebrew
  when: ansible_distribution == 'MacOSX'
  with_items: "{{homebrew_taps}}"
  homebrew_tap: name="{{item}}" state=present

- name: Install packages with homebrew
  tags: homebrew
  when: ansible_distribution == 'MacOSX'
  with_items: "{{homebrew_packages}}"
  homebrew:
    name: "{{item.name}}"
    options: "{{item.options|default()}}"
    state: latest

- name: Install packages with homebrew cask
  tags: homebrew
  when: ansible_distribution == 'MacOSX'
  with_items: "{{homebrew_cask_packages}}"
  homebrew_cask: name="{{item}}" state=installed

- name: Update all packages
  tags: homebrew
  when: ansible_distribution == 'MacOSX'
  homebrew: update_homebrew=yes
