---
- name: MacOSX
  tags: coreutils
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: coreutils
    state: latest

- name: Ubuntu
  tags: coreutils
  become: yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: coreutils
    state: present
