#!/bin/sh

# fix SSH auth socket location so agent forwarding works with tmux
if test "${SSH_AUTH_SOCK}" ; then
    ln -sf "${SSH_AUTH_SOCK}" "${HOME}/.ssh/ssh_auth_sock_$(hostname)"
fi

# The following is a snippet pulled from the sshd man page
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
    else
        # X11UseLocalhost=no
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
