---
- name: MacOSX
  tags: llvm
  when: ansible_distribution == 'MacOSX'
  with_items: "{{packages[ansible_distribution | lower]}}"
  homebrew:
    name: "{{item.name}}"
    state: latest
    options: "{{item.options | default()}}"

- name: Ubuntu
  tags: llvm
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  with_items: "{{packages[ansible_distribution | lower]}}"
  package:
    name: "{{item}}"
    state: latest

- name: Ubuntu
  tags: llvm
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  alternatives:
    name: clang-format
    link: /usr/bin/clang-format
    path: /usr/bin/clang-format-10

- name: Ubuntu
  tags: llvm
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  alternatives:
    name: clang-tidy
    link: /usr/bin/clang-tidy
    path: /usr/bin/clang-tidy-10

- name: Ubuntu
  tags: llvm
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  alternatives:
    name: clangd
    link: /usr/bin/clangd
    path: /usr/bin/clangd-10
