---
- name: MacOSX
  tags: llvm
  when: ansible_distribution == 'MacOSX'
  with_items: "{{packages[ansible_distribution | lower]}}"
  homebrew:
    name: "{{item.name}}"
    state: latest
    options: "{{item.options | default()}}"

- name: Ubuntu
  tags: llvm
  become: yes
  when: ansible_distribution == 'Ubuntu'
  with_items: "{{packages[ansible_distribution | lower]}}"
  package:
    name: "{{item}}"
    state: latest
