---
- name: MacOSX
  tags: haskell
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: haskell-stack
    state: latest

- name: Ubuntu
  tags: haskell
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: haskell-platform
    state: latest
