---
- name: zsh
  tags: zsh
  become: !!bool yes
  package:
    name: zsh
    state: latest

- name: set default shell
  tags: zsh
  lineinfile:
    dest: ~/.profile
    insertafter: EOF
    line: '. ~/.config/shell/profile'
