---
- name: MacOSX
  tags: zsh
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: zsh
    state: latest

- name: openSUSE
  tags: zsh
  become: yes
  when: ansible_distribution == 'openSUSE'
  zypper:
    name: "http://download.opensuse.org/repositories/shells/openSUSE_13.1\
           /x86_64/zsh-5.2-154.1.x86_64.rpm"
    state: present
    disable_recommends: no
