- name: zsh
  homebrew:
    name: zsh
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: openSUSE
  become: true
  zypper:
    name: http://download.opensuse.org/repositories/shells/openSUSE_13.1/x86_64/zsh-5.2-154.1.x86_64.rpm
    state: present
    disable_recommends: no
  when: ansible_distribution == 'openSUSE'
