---
- name: MacOSX
  tags: zsh
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: zsh
    state: latest

- name: Ubuntu
  tags: zsh
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: zsh
    state: latest
