---
- name: MacOSX
  tags: curl
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: curl
    state: latest

- name: Ubuntu
  tags: curl
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: curl
    state: latest
