---
- name: MacOSX
  tags: ag
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: ag
    state: latest

- name: Ubuntu
  tags: ag
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: silversearcher-ag
    state: latest
