---
- name: MacOSX
  homebrew_cask:
    name: vlc
    state: present
  when: ansible_distribution == 'MacOSX'


- name: openSUSE
  become: true
  zypper:
    name: vlc
    state: latest
    disable_recommends: no
  when: ansible_distribution == 'openSUSE'
