- name: MacOSX
  tags: vlc
  when: ansible_distribution == 'MacOSX'
  homebrew_cask:
    name: vlc
    state: present


- name: openSUSE
  tags: vlc
  become: yes
  when: ansible_distribution == 'openSUSE'
  zypper:
    name: vlc
    state: latest
    disable_recommends: no
