---
- name: python 2 package
  tags: yapf
  become: !!bool yes
  pip:
    name: yapf
    executable: "{{pip2_executable[ansible_distribution | lower]\
                 | default([pip2])}}"

- name: python 3 package
  tags: yapf
  become: !!bool yes
  pip:
    name: yapf
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
