---
- name: python 3 package
  tags: dploy
  become: !!bool yes
  pip:
    name: dploy
    state: latest
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
