---
- name: MacOSX
  tags: cmake
  homebrew:
    name: cmake
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: Ubuntu
  tags: cmake
  become: yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: cmake
    state: latest
