---
- name: CMake
  tags: cmake
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  pip:
    name: cmake
    state: latest
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
