"""Generate per-agent instruction files from shared markdown fragments.

Harnesses disagree on how to include one file from another: Claude Code has
`@path` imports, opencode has an `instructions` glob array, and pi has neither.
The lowest common denominator every harness understands is a flat file with the
content actually in it, so the content lives in fragments and each harness gets
a generated file assembled from them.
"""

import pathlib
from typing import NamedTuple

from ruamel.yaml import YAML

FRAGMENT_DIR = pathlib.Path("agents/.config/ai-instructions")
MANIFEST_PATH = FRAGMENT_DIR / "manifest.yaml"

BANNER = (
    "<!-- Generated by `uv run inv gen-instructions` from {sources}.\n"
    "     Edit those fragments, not this file. -->\n"
)

_YAML = YAML()


class Output(NamedTuple):
    """One generated file: its ordered fragments and an optional literal header.

    `header` exists for outputs whose format reserves the first line, such as a
    Claude Code output style needing YAML frontmatter. It is emitted verbatim
    above the banner.
    """

    fragments: list[str]
    header: str | None = None


def _render(text: str) -> str:
    """Transform one fragment on its way into an output.

    Deliberately an identity function. Plain concatenation covers whole-block
    variance between harnesses, which is the only kind this repo has; expressing
    per-harness differences as fragment selection keeps every fragment readable
    on its own. When a fragment first needs inline substitution, this is the one
    place a template engine gets introduced.
    """
    return text


def load_manifest(path: pathlib.Path = MANIFEST_PATH) -> dict[str, Output]:
    """Map each output path to its manifest entry."""
    data = _YAML.load(path) or {}
    outputs = data.get("outputs") or {}
    return {
        out: Output(list(cfg["fragments"]), cfg.get("header"))
        for out, cfg in outputs.items()
    }


def render_output(
    fragments: list[str],
    fragment_dir: pathlib.Path = FRAGMENT_DIR,
    header: str | None = None,
) -> str:
    """Assemble one output file's full text from its fragments."""
    sources = ", ".join(f"{name}.md" for name in fragments)
    banner = BANNER.format(sources=f"{fragment_dir.as_posix()}/{{{sources}}}")
    prefix = f"{header.strip()}\n\n" if header else ""
    bodies = [
        _render((fragment_dir / f"{name}.md").read_text(encoding="utf-8").strip())
        for name in fragments
    ]
    return prefix + banner + "\n" + "\n\n".join(bodies) + "\n"


def generate(
    check: bool = False,
    manifest_path: pathlib.Path = MANIFEST_PATH,
    fragment_dir: pathlib.Path = FRAGMENT_DIR,
) -> list[str]:
    """Write every output in the manifest, or report drift when check is set.

    Returns the output paths whose on-disk content does not match their
    fragments. Always empty when check is False, because they were just written.
    """
    drift = []
    for out, spec in load_manifest(manifest_path).items():
        expected = render_output(spec.fragments, fragment_dir, spec.header)
        path = pathlib.Path(out)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        if check:
            drift.append(out)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    return drift
