---
- name: Ubuntu - Auto-Hide Launcher
  tags: ubuntu
  when: ansible_distribution == 'Ubuntu'
  command: dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-hide-mode 1

- name: Ubuntu - Auto-Lock Screen After 20 Minutes
  tags: ubuntu
  when: ansible_distribution == 'Ubuntu'
  command: conf write /org/gnome/desktop/session/idle-delay 1200
