---
- name: MacOSX
  tags: ruby
  when: ansible_distribution == 'MacOSX'
  with_items: "{{packages[ansible_distribution | lower]}}"
  homebrew:
    name: "{{item}}"
    state: latest

- name: Ubuntu
  tags: ruby
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  with_items: "{{packages[ansible_distribution | lower]}}"
  package:
    name: "{{item}}"
    state: latest
