---
- name: MacOSX
  tags: ruby
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: ruby
    state: latest

- name: Ubuntu
  tags: ruby
  become: yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: ruby
    state: latest
