- name: MacOSX
  tags: dropbox
  when: ansible_distribution == 'MacOSX'
  homebrew_cask:
    name: dropbox
    state: present

- name: openSUSE
  tags: dropbox
  become: true
  when: ansible_distribution == 'openSUSE'
  zypper:
    name: dropbox
    state: latest
    disable_recommends: no

