- name: MacOSX
  homebrew_cask:
    name: dropbox
    state: present
  when: ansible_distribution == 'MacOSX'

- name: openSUSE
  become: true
  zypper:
    name: dropbox
    state: latest
    disable_recommends: no
  when: ansible_distribution == 'openSUSE'

