---
- name: MacOSX
  tags: neovim
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: neovim/neovim/neovim
    state: latest

- name: python 3 package
  tags: dploy
  become: yes
  pip:
    name: dploy
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
