---
- name: MacOSX
  tags: neovim
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: neovim/neovim/neovim
    state: latest

- name: Ubuntu
  tags: neovim
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: software-properties-common
    state: latest

- name: Ubuntu
  tags: neovim
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
    update_cache: !!bool yes

- name: Ubuntu
  tags: neovim
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: neovim
    state: latest

- name: python 3 package
  tags: neovim
  become: !!bool yes
  pip:
    state: latest
    name: neovim
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"

- name: python 2 package
  tags: neovim
  become: !!bool yes
  pip:
    name: neovim
    state: latest
    executable: "{{pip2_executable[ansible_distribution | lower]\
                 | default([pip2])}}"

- name: ruby package
  tags: neovim
  become: !!bool yes
  gem:
    name: neovim
    state: latest
