---
- name: MacOSX
  tags: spectacle
  when: ansible_distribution == 'MacOSX'
  homebrew_cask:
    name: spectacle
    state: present

- name: MacOSX
  tags: spectacle
  when: ansible_distribution == 'MacOSX'
  script: add_to_login_items.sh
  become: yes
