---
- name: ssh
  tags: ssh
  become: !!bool yes
  package:
    name: openssh-server
    state: latest


# ssh-askpass is used when ssh-add is called during start-up to prompt for the
# ssh passphrase.
- name: ssh
  tags: ssh
  become: !!bool yes
  package:
    name: ssh-askpass
    state: latest
