- name: Zypper Add Additional Repositories
  tags: zypper
  become: true
  with_items: "{{zypper_repositories}}"
  when: ansible_distribution == "openSUSE"
  zypper_repository:
    name: "{{item.name}}"
    refresh: true
    repo: "{{item.repo}}"
    state: present

- name: Zypper Install General Packages
  tags: zypper
  become: true
  with_items: "{{zypper_packages}}"
  when: ansible_distribution == "openSUSE"
  zypper:
    name: "{{item}}"
    state: latest
    disable_recommends: false
