- name: Zypper Add Additional Repositories
  become: yes
  zypper_repository:
    name: "{{item.name}}"
    refresh: yes
    repo: "{{item.repo}}"
    state: present
  with_items: "{{zypper_repositories}}"
  when: ansible_distribution == "openSUSE"

- name: Zypper Install General Packages
  become: true
  zypper: name="{{item}}" state=latest disable_recommends=no
  with_items: "{{zypper_packages}}"
  when: ansible_distribution == "openSUSE"
