- name: Zypper Install General Packages
  zypper: name={{item}} state=latest disable_recommends=no
  with_items: zypper_packages

- name: Zypper Install Specific Packages
  zypper: name={{item}} state=present disable_recommends=no
  with_items: zypper_specifc_packages
  ignore_errors: yes
