- name: Zypper Add Additional Repositories
  tags: zypper
  become: yes
  with_items: "{{zypper_repositories}}"
  when: ansible_distribution == "openSUSE"
  zypper_repository:
    name: "{{item.name}}"
    refresh: yes
    repo: "{{item.repo}}"
    state: present
