---
- name: python 3 package
  tags: yamllint
  become: !!bool yes
  pip:
    name: yamllint
    state: latest
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
