---
- name: MacOSX
  tags: unrar
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: unrar
    state: latest

- name: Ubuntu
  tags: unrar
  become: yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: unrar
    state: latest
