homebrew_taps:
  - caskroom/cask
  - caskroom/versions
  - homebrew/dupes

homebrew_packages:

    # mac specific
  - {name: 'coreutils'}
  - {name: 'git'}

    # for pygame
  - {name: 'portmidi'}

homebrew_cask_packages:
  - vlc
  - transmission
