---
- name: python 3 package
  tags: vint
  become: !!bool yes
  pip:
    name: vim-vint
    state: latest
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
