---
- name: MacOSX
  tags: ack
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: ack
    state: latest

- name: Ubuntu
  tags: ack
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: ack-grep
    state: latest
