---
pip_modules:
  # python 3 prefered
  - dploy
  - pylint
  - invoke

  # both
  - gitpython


  # python 2 only
  # - scons
  # - ansible

pip_modules_osx:
  # - 'hg+http://bitbucket.org/pygame/pygame#egg=pygame'

