---
- name: python 2 package
  tags: python_git
  become: !!bool yes
  pip:
    name: gitpython
    state: latest
    executable: "{{pip2_executable[ansible_distribution | lower]\
                 | default([pip2])}}"

- name: python 3 package
  tags: python_git
  become: !!bool yes
  pip:
    name: gitpython
    state: latest
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
