- name: python 2 package
  tags: python_git
  become: yes
  pip:
    name: gitpython
    executable: "{{pip2_executable[ansible_distribution | lower] | default([pip2])}}"

- name: python 3 package
  tags: python_git
  become: yes
  pip:
    name: gitpython
    executable: "{{pip3_executable[ansible_distribution | lower] | default([pip3])}}"
