- name: MacOSX
  tags: htop
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: htop
    state: latest


- name: openSUSE
  tags: htop
  become: yes
  when: ansible_distribution == 'openSUSE'
  zypper:
    name: htop
    state: latest
    disable_recommends: no
