- name: MacOSX
  homebrew:
    name: htop
    state: latest
  when: ansible_distribution == 'MacOSX'


- name: openSUSE
  become: true
  zypper:
    name: htop
    state: latest
    disable_recommends: no
  when: ansible_distribution == 'openSUSE'
