---
- name: MacOSX
  tags: tmux
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: tmux
    state: latest

- name: Ubuntu
  tags: tmux
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: tmux
    state: latest
