- name: MacOSX
  tags: tmux
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: tmux
    state: latest

- name: openSUSE
  tags: tmux
  become: true
  when: ansible_distribution == 'openSUSE'
  zypper:
    name: http://download.opensuse.org/repositories/utilities/openSUSE_13.1/x86_64/tmux-2.1-4.1.x86_64.rpm
    state: present
    disable_recommends: no
