---
- name: pip
  tags: pip
  become: !!bool yes
  when: ansible_distribution == "Ubuntu"
  with_items: "{{packages}}"
  package:
    name: "{{item}}"
    state: latest

- name: python 3 package
  tags: pip
  become: !!bool yes
  pip:
    name: pip
    state: latest
    executable: "{{pip3_executable[ansible_distribution | lower]\
                 | default([pip3])}}"
