- name: python 2 packages
  pip: name="{{item}}"
  with_items: "{{pip_modules}}"

- name: python 3 packages
  pip: name="{{item}}"
  with_items: "{{pip_modules}}"

- name: python 3 only packages
  pip: name="{{item}}" executable=pip3
  with_items: "{{pip3_modules}}"

- name: python 2 only packages
  pip: name="{{item}}" executable=pip2
  with_items: "{{pip2_modules}}"
