- name: python 2 packages
  tags: pip
  with_items: "{{pip_modules}}"
  pip:
    name: "{{item}}"
    executable: "{{pip2_executable[ansible_distribution | lower] | default([pip2])}}"

- name: python 2 only packages
  tags: pip
  with_items: "{{pip2_modules}}"
  pip:
    name: "{{item}}"
    executable: "{{pip2_executable[ansible_distribution | lower] | default([pip2])}}"

- name: python 3 packages
  tags: pip
  with_items: "{{pip_modules}}"
  pip:
    name: "{{item}}"
    executable: "{{pip3_executable[ansible_distribution | lower] | default([pip3])}}"

- name: python 3 only packages
  tags: pip
  with_items: "{{pip3_modules}}"
  pip:
    name: "{{item}}"
    executable: "{{pip3_executable[ansible_distribution | lower] | default([pip3])}}"
