- name: python 2 packages
  pip: name="{{item}}" executable="{{pip2_executable[ansible_distribution | lower] | default([pip2])}}"
  with_items: "{{pip_modules}}"
  become: true

- name: python 2 only packages
  pip: name="{{item}}" executable="{{pip2_executable[ansible_distribution|lower] | default([pip2])}}"
  with_items: "{{pip2_modules}}"
  become: true

- name: python 3 packages
  pip: name="{{item}}" executable="{{pip3_executable[ansible_distribution|lower] | default([pip3])}}"
  with_items: "{{pip_modules}}"
  become: true

- name: python 3 only packages
  pip: name="{{item}}" executable="{{pip3_executable[ansible_distribution|lower] | default([pip3])}}"
  with_items: "{{pip3_modules}}"
  become: true
