---
- name: Check if rustup is installed
  become: false
  ansible.builtin.command:
    cmd: rustup --version
  tags: [neovim, rust, rustup]
  register: rustup_check
  changed_when: false
  failed_when: false
  when: not is_termux

- name: Install rustup
  become: false
  when: not is_termux and rustup_check.rc != 0
  tags: [neovim, rust, rustup]
  ansible.builtin.shell:
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ user_home }}/.cargo/bin/rustup"

- name: Check if bob is installed
  become: false
  ansible.builtin.command:
    cmd: "{{ user_home }}/.cargo/bin/bob --version"
  tags: [neovim, bob]
  register: bob_check
  changed_when: false
  failed_when: false
  when: not is_termux

- name: Install bob-nvim via cargo
  become: false
  when: not is_termux and bob_check.rc != 0
  tags: [neovim, bob]
  ansible.builtin.command:
    cmd: "{{ user_home }}/.cargo/bin/cargo install bob-nvim"

- name: Install stable Neovim via bob
  become: false
  when: not is_termux
  tags: [neovim, bob]
  ansible.builtin.command:
    cmd: "{{ user_home }}/.cargo/bin/bob install stable"
  register: bob_install
  changed_when: "'already installed' not in bob_install.stdout"

- name: Use stable Neovim via bob
  become: false
  when: not is_termux
  tags: [neovim, bob]
  ansible.builtin.command:
    cmd: "{{ user_home }}/.cargo/bin/bob use stable"
  changed_when: false
