---
- name: Source shell profile from .profile
  become: false
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.profile"
    insertafter: EOF
    line: ". ~/.config/shell/profile"
    create: true
    mode: "0644"
