- name: picocom
  homebrew:
    name: picocom
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: picocom
  zypper:
    name: picocom
    state: latest
    disable_recommends: no
  when: ansible_distribution == 'OpenSuse'

