---
- name: MacOSX
  tags: python
  when: ansible_distribution == 'MacOSX'
  with_items: "{{packages}}"
  homebrew:
    name: "{{item}}"
    state: latest

- name: openSUSE
  tags: python
  become: yes
  when: ansible_distribution == "openSUSE"
  with_items: "{{packages}}"
  zypper:
    name: "{{item}}"
    state: present
    disable_recommends: no
