- name: MacOSX hombrew
  tags: pygame
  when: ansible_distribution == 'MacOSX'
  with_items: "{{homebrew_packages}}"
  homebrew:
    name: "{{item}}"
    state: latest

- name: MacOSX python 3
  tags: pygame
  become: yes
  when: ansible_distribution == 'MacOSX'
  with_items: "{{pip_modules_mac}}"
  pip:
    name: "{{item}}"
    executable: pip3

- name: MacOSX python 2
  tags: pygame
  become: yes
  when: ansible_distribution == 'MacOSX'
  with_items: "{{pip_modules_mac}}"
  pip:
    name: "{{item}}"
    executable: pip2
