---
- name: MacOSX
  tags: git
  homebrew:
    name: git
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: Ubuntu
  tags: git
  become: yes
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present
    update_cache: yes

- name: Ubuntu
  tags: git
  become: yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: git
    state: latest
