- name: Clone or Update Git Repositories
  git:
    repo: "{{item.repo}}"
    dest: "{{item.dest}}"
    version: "{{item.version}}"
    force: no
    update: no
  with_items: "{{git_repositories}}"
  ignore_errors: yes
