---
- name: git package repo
  tags: git
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present
    update_cache: !!bool yes

- name: git
  tags: git
  become: !!bool yes
  package:
    name: git
    state: latest
