- name: htop
  homebrew:
    name: git
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: htop
  zypper:
    name: git
    state: latest
    disable_recommends: no
  when: ansible_distribution == 'OpenSuse'
