- name: MacOSX
  homebrew:
    name: git
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: openSUSE
  become: true
  zypper:
    name: git
    state: latest
    disable_recommends: no
  when: ansible_distribution == 'openSUSE'
