---
- name: MacOSX
  tags: git
  homebrew:
    name: git
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: openSUSE
  tags: git
  become: yes
  zypper:
    name: git
    state: latest
    disable_recommends: no
  when: ansible_distribution == 'openSUSE'
