---
- name: vim
  tags: vim
  become: !!bool yes

  apt_repository:
    repo: 'ppa:jonathonf/vim'
    state: present
    update_cache: !!bool yes

- name: vim
  tags: vim
  become: !!bool yes
  package:
    name: vim
    state: latest
