---
- name: MacOSX
  tags: vim
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: vim
    options: with-lua
    state: latest

- name: openSUSE
  tags: vim
  become: yes
  when: ansible_distribution == 'openSUSE'
  zypper:
    name: "http://download.opensuse.org/repositories/editors/openSUSE_13.1\
           /x86_64/vim-7.4.1294-313.1.x86_64.rpm"
    state: present
    disable_recommends: no
