---
- name: MacOSX
  tags: vim
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: vim
    options: with-lua
    state: latest

- name: Ubuntu
  tags: vim-gnome
  become: yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: vim-gnome
    state: latest
