- name: MacOSX
  homebrew:
    name: vim
    options: with-lua
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: openSUSE
  become: true
  zypper:
    name: http://download.opensuse.org/repositories/editors/openSUSE_13.1/x86_64/vim-7.4.1294-313.1.x86_64.rpm
    state: present
    disable_recommends: no
  when: ansible_distribution == 'openSUSE'
