---
- name: docker
  tags: docker
  become: !!bool yes
  package:
    name: docker
    state: latest

- name: docker group
  group:
    become: !!bool yes
    name: docker
    state: present

- name: docker user added to group
  user:
    become: !!bool yes
    name: "{{ lookup('env','USER') }}"
    group: docker
    append: !!bool yes
