---
- hosts: all
  connection: local
  vars_prompt:
     - name: "username"
       prompt: "USERNAME"
  vars:
    system: 'osx'
  roles:
      - ack
      - ag
      - appcleaner
      - chrome
      - coreutils
      - cscope
      - curl
      - dash
      - dropbox
      - firefox
      - git
      - hg
      - homebrew
      - htop
      - httpie
      - iterm2
      - licecap
      - lua
      - moreutils
      - mutt
      - neovim
      - pip
      - pstree
      - pygame
      - python2
      - python3
      - reattach-to-user-namespace
      - ruby
      - sdl
      - set_default_shell_osx
      - skype
      - spectacle
      - tmp
      - tmux
      - transmission
      - tree
      - vim
      - vlc
      - wget
      - xquartz
      - zsh
