---
- name: Configure workstation
  hosts: localhost
  connection: local
  become: true
  tasks:
    - ansible.builtin.import_tasks: tasks/repos.yml
    - ansible.builtin.import_tasks: tasks/packages.yml
    - ansible.builtin.import_tasks: tasks/neovim.yml
    - ansible.builtin.import_tasks: tasks/yarn.yml
    - ansible.builtin.import_tasks: tasks/uv.yml
    - ansible.builtin.import_tasks: tasks/pip-packages.yml
    - ansible.builtin.import_tasks: tasks/pnpm-packages.yml
    - ansible.builtin.import_tasks: tasks/zsh.yml
