---
- name: Configure workstation
  hosts: localhost
  connection: local
  become: "{{ ansible_os_family != 'Android' }}"
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: Verify sudo access
      ansible.builtin.command:
        cmd: whoami
      changed_when: false
      register: sudo_check
      failed_when: sudo_check.stdout != "root"
      when: ansible_os_family != 'Android'

    - ansible.builtin.import_tasks: tasks/repos.yml
    - ansible.builtin.import_tasks: tasks/packages.yml
    - ansible.builtin.import_tasks: tasks/neovim.yml
    - ansible.builtin.import_tasks: tasks/python-packages.yml
    - ansible.builtin.import_tasks: tasks/javascript-packages.yml
    - ansible.builtin.import_tasks: tasks/zsh.yml
