---
- name: MacOSX
  tags: shellcheck
  when: ansible_distribution == 'MacOSX'
  homebrew:
    name: shellcheck
    state: latest

- name: Ubuntu
  tags: shellcheck
  become: !!bool yes
  when: ansible_distribution == 'Ubuntu'
  package:
    name: shellcheck
    state: latest
