- name: Clone or Update Git Repositories
  tags: git_repos
  ignore_errors: true
  with_items: "{{git_repositories}}"
  git:
    repo: "{{item.repo}}"
    dest: "{{item.dest}}"
    version: "{{item.version}}"
    force: no
    update: no
