---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt-get install python3-setuptools
          sudo apt-get install python3
          sudo apt-get install python3-pip
          sudo apt-get install python3-venv
          sudo pip3 install poetry
          poetry install
      - name: test
        run: |
          poetry run invoke
          poetry run invoke stow
