"""Generating the adapters' copy of the catalog framing.

The preamble and delimiters are the one structural control over untrusted index
text: they are what tells a model the enclosed Markdown is a catalog of
references and not instructions. The pi extension renders a project catalog
without the CLI, so that text has to exist in TypeScript too.

Generated rather than copied. A second hand-maintained copy of a security
boundary drifts, and the drift is silent -- the wording still looks plausible
while no longer matching what the resolver emits.
"""

import json
import pathlib

from manage.knowledge import resolver

TARGET = pathlib.Path(
    "pi/.pi/agent/extensions/agent-knowledge/framing.ts"
)

_BANNER = (
    "// Generated by `uv run inv gen-framing` from manage/knowledge/resolver.py.\n"
    "// Edit the resolver constants in that file, not this one.\n"
    "//\n"
    "// The fence is what separates untrusted index text from the instructions\n"
    "// around it, so this must stay byte-identical to what the CLI emits: a\n"
    "// project catalog rendered here and one rendered there are the same contract.\n"
)


def render():
    """The TypeScript module text for the current framing constants."""
    # json.dumps, not repr: repr picks single quotes for a string containing an
    # apostrophe, and rewriting quotes afterwards would corrupt the apostrophe.
    # JSON string syntax is a subset of TypeScript's.
    return (
        f"{_BANNER}\n"
        'import { randomBytes } from "node:crypto";\n\n'
        f"export const BEGIN_MARKER = {json.dumps(resolver.BEGIN_MARKER)};\n"
        f"export const END_MARKER = {json.dumps(resolver.END_MARKER)};\n\n"
        f"export const PREAMBLE = {json.dumps(resolver.PREAMBLE)};\n\n"
        "/** A fresh fence, so bundle content cannot predict how it is quoted. */\n"
        "export function newFence(): string {\n"
        f'\treturn randomBytes({resolver.FENCE_BYTES}).toString("hex");\n'
        "}\n"
    )


def generate(check=False, target=TARGET):
    """Write the generated module, or report drift when `check` is set.

    Returns 1 when `check` finds drift, so a task can exit on it.
    """
    target = pathlib.Path(target)
    expected = render()
    current = target.read_text(encoding="utf-8") if target.exists() else None
    if current == expected:
        return 0
    if check:
        print(f"{target} is stale; run `uv run inv gen-framing`")
        return 1
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8")
    print(f"Wrote {target}")
    return 0
